name = "eduvidual-to-todoist"
main = "src/worker.ts"
compatibility_date = "2024-11-01"

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[triggers]
crons = ["0 */3 * * *"]

[[kv_namespaces]]
binding = "SYNC_STATE"
id = "cd25df842bb8423bbdc42da43a2fb1f9"
